// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: oss/v1/download.proto

package ossv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ObjectId string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// Range: 起始offset(包含)
	StartOffset uint64 `protobuf:"varint,2,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	// 结束 offset(可选，包含/不包含需要统一规定)
	// recommend: end_offset为包含式或半开区间二选一，下面按半开区间写
	EndOffset uint64 `protobuf:"varint,3,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	HasEnd    bool   `protobuf:"varint,4,opt,name=has_end,json=hasEnd,proto3" json:"has_end,omitempty"`
	// 建议的chunk大小(服务端可忽略或裁剪)
	PreferredChunkSize uint32 `protobuf:"varint,5,opt,name=preferred_chunk_size,json=preferredChunkSize,proto3" json:"preferred_chunk_size,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_oss_v1_download_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oss_v1_download_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_oss_v1_download_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *DownloadRequest) GetStartOffset() uint64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *DownloadRequest) GetEndOffset() uint64 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *DownloadRequest) GetHasEnd() bool {
	if x != nil {
		return x.HasEnd
	}
	return false
}

func (x *DownloadRequest) GetPreferredChunkSize() uint32 {
	if x != nil {
		return x.PreferredChunkSize
	}
	return 0
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // 这块payload对应文件的起始offset(便于校验/断点)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_oss_v1_download_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_oss_v1_download_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_oss_v1_download_proto_rawDescGZIP(), []int{1}
}

func (x *FileChunk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FileChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_oss_v1_download_proto protoreflect.FileDescriptor

const file_oss_v1_download_proto_rawDesc = "" +
	"\n" +
	"\x15oss/v1/download.proto\x12\x06oss.v1\"\xbb\x01\n" +
	"\x0fDownloadRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12!\n" +
	"\fstart_offset\x18\x02 \x01(\x04R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x03 \x01(\x04R\tendOffset\x12\x17\n" +
	"\ahas_end\x18\x04 \x01(\bR\x06hasEnd\x120\n" +
	"\x14preferred_chunk_size\x18\x05 \x01(\rR\x12preferredChunkSize\"=\n" +
	"\tFileChunk\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset2M\n" +
	"\x0fDownloadService\x12:\n" +
	"\bDownload\x12\x17.oss.v1.DownloadRequest\x1a\x11.oss.v1.FileChunk\"\x000\x01B<Z:github.com/aureate7/mini-oss/service_proto/pb/oss/v1;ossv1b\x06proto3"

var (
	file_oss_v1_download_proto_rawDescOnce sync.Once
	file_oss_v1_download_proto_rawDescData []byte
)

func file_oss_v1_download_proto_rawDescGZIP() []byte {
	file_oss_v1_download_proto_rawDescOnce.Do(func() {
		file_oss_v1_download_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oss_v1_download_proto_rawDesc), len(file_oss_v1_download_proto_rawDesc)))
	})
	return file_oss_v1_download_proto_rawDescData
}

var file_oss_v1_download_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oss_v1_download_proto_goTypes = []any{
	(*DownloadRequest)(nil), // 0: oss.v1.DownloadRequest
	(*FileChunk)(nil),       // 1: oss.v1.FileChunk
}
var file_oss_v1_download_proto_depIdxs = []int32{
	0, // 0: oss.v1.DownloadService.Download:input_type -> oss.v1.DownloadRequest
	1, // 1: oss.v1.DownloadService.Download:output_type -> oss.v1.FileChunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oss_v1_download_proto_init() }
func file_oss_v1_download_proto_init() {
	if File_oss_v1_download_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oss_v1_download_proto_rawDesc), len(file_oss_v1_download_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oss_v1_download_proto_goTypes,
		DependencyIndexes: file_oss_v1_download_proto_depIdxs,
		MessageInfos:      file_oss_v1_download_proto_msgTypes,
	}.Build()
	File_oss_v1_download_proto = out.File
	file_oss_v1_download_proto_goTypes = nil
	file_oss_v1_download_proto_depIdxs = nil
}
