// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.20.3
// source: oss/v1/upload_session.proto

package ossv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UploadSessionService_CreateUploadSession_FullMethodName = "/oss.v1.UploadSessionService/CreateUploadSession"
	UploadSessionService_GetUploadSession_FullMethodName    = "/oss.v1.UploadSessionService/GetUploadSession"
)

// UploadSessionServiceClient is the client API for UploadSessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UploadSessionServiceClient interface {
	CreateUploadSession(ctx context.Context, in *CreateUploadSessionRequest, opts ...grpc.CallOption) (*CreateUploadSessionResponse, error)
	GetUploadSession(ctx context.Context, in *GetUploadSessionRequest, opts ...grpc.CallOption) (*GetUploadSessionResponse, error)
}

type uploadSessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUploadSessionServiceClient(cc grpc.ClientConnInterface) UploadSessionServiceClient {
	return &uploadSessionServiceClient{cc}
}

func (c *uploadSessionServiceClient) CreateUploadSession(ctx context.Context, in *CreateUploadSessionRequest, opts ...grpc.CallOption) (*CreateUploadSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUploadSessionResponse)
	err := c.cc.Invoke(ctx, UploadSessionService_CreateUploadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadSessionServiceClient) GetUploadSession(ctx context.Context, in *GetUploadSessionRequest, opts ...grpc.CallOption) (*GetUploadSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUploadSessionResponse)
	err := c.cc.Invoke(ctx, UploadSessionService_GetUploadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UploadSessionServiceServer is the server API for UploadSessionService service.
// All implementations must embed UnimplementedUploadSessionServiceServer
// for forward compatibility.
type UploadSessionServiceServer interface {
	CreateUploadSession(context.Context, *CreateUploadSessionRequest) (*CreateUploadSessionResponse, error)
	GetUploadSession(context.Context, *GetUploadSessionRequest) (*GetUploadSessionResponse, error)
	mustEmbedUnimplementedUploadSessionServiceServer()
}

// UnimplementedUploadSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUploadSessionServiceServer struct{}

func (UnimplementedUploadSessionServiceServer) CreateUploadSession(context.Context, *CreateUploadSessionRequest) (*CreateUploadSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUploadSession not implemented")
}
func (UnimplementedUploadSessionServiceServer) GetUploadSession(context.Context, *GetUploadSessionRequest) (*GetUploadSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUploadSession not implemented")
}
func (UnimplementedUploadSessionServiceServer) mustEmbedUnimplementedUploadSessionServiceServer() {}
func (UnimplementedUploadSessionServiceServer) testEmbeddedByValue()                              {}

// UnsafeUploadSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UploadSessionServiceServer will
// result in compilation errors.
type UnsafeUploadSessionServiceServer interface {
	mustEmbedUnimplementedUploadSessionServiceServer()
}

func RegisterUploadSessionServiceServer(s grpc.ServiceRegistrar, srv UploadSessionServiceServer) {
	// If the following call panics, it indicates UnimplementedUploadSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UploadSessionService_ServiceDesc, srv)
}

func _UploadSessionService_CreateUploadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadSessionServiceServer).CreateUploadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UploadSessionService_CreateUploadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadSessionServiceServer).CreateUploadSession(ctx, req.(*CreateUploadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UploadSessionService_GetUploadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadSessionServiceServer).GetUploadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UploadSessionService_GetUploadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadSessionServiceServer).GetUploadSession(ctx, req.(*GetUploadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UploadSessionService_ServiceDesc is the grpc.ServiceDesc for UploadSessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UploadSessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oss.v1.UploadSessionService",
	HandlerType: (*UploadSessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUploadSession",
			Handler:    _UploadSessionService_CreateUploadSession_Handler,
		},
		{
			MethodName: "GetUploadSession",
			Handler:    _UploadSessionService_GetUploadSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oss/v1/upload_session.proto",
}
