// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: oss/v1/upload.proto

package ossv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Checksum32    uint32                 `protobuf:"varint,4,opt,name=checksum32,proto3" json:"checksum32,omitempty"`       // 检验片段
	IsLast        bool                   `protobuf:"varint,5,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"` // 是否最后一块chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_oss_v1_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_oss_v1_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_oss_v1_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadChunk) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *UploadChunk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadChunk) GetChecksum32() uint32 {
	if x != nil {
		return x.Checksum32
	}
	return 0
}

func (x *UploadChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type UploadFileResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"` // 最终文件校验
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResult) Reset() {
	*x = UploadFileResult{}
	mi := &file_oss_v1_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResult) ProtoMessage() {}

func (x *UploadFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_oss_v1_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResult.ProtoReflect.Descriptor instead.
func (*UploadFileResult) Descriptor() ([]byte, []int) {
	return file_oss_v1_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileResult) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *UploadFileResult) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadFileResult) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadFileResult) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UploadFileResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_oss_v1_upload_proto protoreflect.FileDescriptor

const file_oss_v1_upload_proto_rawDesc = "" +
	"\n" +
	"\x13oss/v1/upload.proto\x12\x06oss.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x01\n" +
	"\vUploadChunk\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1e\n" +
	"\n" +
	"checksum32\x18\x04 \x01(\rR\n" +
	"checksum32\x12\x17\n" +
	"\ais_last\x18\x05 \x01(\bR\x06isLast\"\xb7\x01\n" +
	"\x10UploadFileResult\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt2L\n" +
	"\rUploadService\x12;\n" +
	"\x06Upload\x12\x13.oss.v1.UploadChunk\x1a\x18.oss.v1.UploadFileResult\"\x00(\x01B<Z:github.com/aureate7/mini-oss/service_proto/pb/oss/v1;ossv1b\x06proto3"

var (
	file_oss_v1_upload_proto_rawDescOnce sync.Once
	file_oss_v1_upload_proto_rawDescData []byte
)

func file_oss_v1_upload_proto_rawDescGZIP() []byte {
	file_oss_v1_upload_proto_rawDescOnce.Do(func() {
		file_oss_v1_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oss_v1_upload_proto_rawDesc), len(file_oss_v1_upload_proto_rawDesc)))
	})
	return file_oss_v1_upload_proto_rawDescData
}

var file_oss_v1_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oss_v1_upload_proto_goTypes = []any{
	(*UploadChunk)(nil),           // 0: oss.v1.UploadChunk
	(*UploadFileResult)(nil),      // 1: oss.v1.UploadFileResult
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_oss_v1_upload_proto_depIdxs = []int32{
	2, // 0: oss.v1.UploadFileResult.completed_at:type_name -> google.protobuf.Timestamp
	0, // 1: oss.v1.UploadService.Upload:input_type -> oss.v1.UploadChunk
	1, // 2: oss.v1.UploadService.Upload:output_type -> oss.v1.UploadFileResult
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_oss_v1_upload_proto_init() }
func file_oss_v1_upload_proto_init() {
	if File_oss_v1_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oss_v1_upload_proto_rawDesc), len(file_oss_v1_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oss_v1_upload_proto_goTypes,
		DependencyIndexes: file_oss_v1_upload_proto_depIdxs,
		MessageInfos:      file_oss_v1_upload_proto_msgTypes,
	}.Build()
	File_oss_v1_upload_proto = out.File
	file_oss_v1_upload_proto_goTypes = nil
	file_oss_v1_upload_proto_depIdxs = nil
}
