// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: oss/v1/upload_session.proto

package ossv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadSessionStatus int32

const (
	UploadSessionStatus_UPLOAD_SESSION_STATUS_UNSPECIFIED UploadSessionStatus = 0
	UploadSessionStatus_UPLOAD_SESSION_STATUS_UPLOADING   UploadSessionStatus = 1
	UploadSessionStatus_UPLOAD_SESSION_STATUS_COMPLETED   UploadSessionStatus = 2
	UploadSessionStatus_UPLOAD_SESSION_STATUS_ABORTED     UploadSessionStatus = 3
)

// Enum value maps for UploadSessionStatus.
var (
	UploadSessionStatus_name = map[int32]string{
		0: "UPLOAD_SESSION_STATUS_UNSPECIFIED",
		1: "UPLOAD_SESSION_STATUS_UPLOADING",
		2: "UPLOAD_SESSION_STATUS_COMPLETED",
		3: "UPLOAD_SESSION_STATUS_ABORTED",
	}
	UploadSessionStatus_value = map[string]int32{
		"UPLOAD_SESSION_STATUS_UNSPECIFIED": 0,
		"UPLOAD_SESSION_STATUS_UPLOADING":   1,
		"UPLOAD_SESSION_STATUS_COMPLETED":   2,
		"UPLOAD_SESSION_STATUS_ABORTED":     3,
	}
)

func (x UploadSessionStatus) Enum() *UploadSessionStatus {
	p := new(UploadSessionStatus)
	*p = x
	return p
}

func (x UploadSessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadSessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_oss_v1_upload_session_proto_enumTypes[0].Descriptor()
}

func (UploadSessionStatus) Type() protoreflect.EnumType {
	return &file_oss_v1_upload_session_proto_enumTypes[0]
}

func (x UploadSessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadSessionStatus.Descriptor instead.
func (UploadSessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_oss_v1_upload_session_proto_rawDescGZIP(), []int{0}
}

type UploadSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	FileSize      uint64                 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ChunkSize     uint32                 `protobuf:"varint,4,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	Offset        uint64                 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Status        UploadSessionStatus    `protobuf:"varint,6,opt,name=status,proto3,enum=oss.v1.UploadSessionStatus" json:"status,omitempty"`
	Sha256        string                 `protobuf:"bytes,7,opt,name=sha256,proto3" json:"sha256,omitempty"` // 幂等匹配
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSession) Reset() {
	*x = UploadSession{}
	mi := &file_oss_v1_upload_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSession) ProtoMessage() {}

func (x *UploadSession) ProtoReflect() protoreflect.Message {
	mi := &file_oss_v1_upload_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSession.ProtoReflect.Descriptor instead.
func (*UploadSession) Descriptor() ([]byte, []int) {
	return file_oss_v1_upload_session_proto_rawDescGZIP(), []int{0}
}

func (x *UploadSession) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *UploadSession) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadSession) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadSession) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *UploadSession) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *UploadSession) GetStatus() UploadSessionStatus {
	if x != nil {
		return x.Status
	}
	return UploadSessionStatus_UPLOAD_SESSION_STATUS_UNSPECIFIED
}

func (x *UploadSession) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UploadSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UploadSession) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UploadSession) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateUploadSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ObjectId       string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	FileSize       uint64                 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	PreferredChunk uint32                 `protobuf:"varint,4,opt,name=preferred_chunk,json=preferredChunk,proto3" json:"preferred_chunk,omitempty"`
	Sha256         string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"` // 幂等性校验
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUploadSessionRequest) Reset() {
	*x = CreateUploadSessionRequest{}
	mi := &file_oss_v1_upload_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadSessionRequest) ProtoMessage() {}

func (x *CreateUploadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oss_v1_upload_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadSessionRequest) Descriptor() ([]byte, []int) {
	return file_oss_v1_upload_session_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUploadSessionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateUploadSessionRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *CreateUploadSessionRequest) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *CreateUploadSessionRequest) GetPreferredChunk() uint32 {
	if x != nil {
		return x.PreferredChunk
	}
	return 0
}

func (x *CreateUploadSessionRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type GetUploadSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"` //  string idempotency_key = 2;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadSessionRequest) Reset() {
	*x = GetUploadSessionRequest{}
	mi := &file_oss_v1_upload_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadSessionRequest) ProtoMessage() {}

func (x *GetUploadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oss_v1_upload_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadSessionRequest.ProtoReflect.Descriptor instead.
func (*GetUploadSessionRequest) Descriptor() ([]byte, []int) {
	return file_oss_v1_upload_session_proto_rawDescGZIP(), []int{2}
}

func (x *GetUploadSessionRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type CreateUploadSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *UploadSession         `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Reused        bool                   `protobuf:"varint,2,opt,name=reused,proto3" json:"reused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadSessionResponse) Reset() {
	*x = CreateUploadSessionResponse{}
	mi := &file_oss_v1_upload_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadSessionResponse) ProtoMessage() {}

func (x *CreateUploadSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oss_v1_upload_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadSessionResponse) Descriptor() ([]byte, []int) {
	return file_oss_v1_upload_session_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUploadSessionResponse) GetSession() *UploadSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *CreateUploadSessionResponse) GetReused() bool {
	if x != nil {
		return x.Reused
	}
	return false
}

type GetUploadSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *UploadSession         `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadSessionResponse) Reset() {
	*x = GetUploadSessionResponse{}
	mi := &file_oss_v1_upload_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadSessionResponse) ProtoMessage() {}

func (x *GetUploadSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oss_v1_upload_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadSessionResponse.ProtoReflect.Descriptor instead.
func (*GetUploadSessionResponse) Descriptor() ([]byte, []int) {
	return file_oss_v1_upload_session_proto_rawDescGZIP(), []int{4}
}

func (x *GetUploadSessionResponse) GetSession() *UploadSession {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_oss_v1_upload_session_proto protoreflect.FileDescriptor

const file_oss_v1_upload_session_proto_rawDesc = "" +
	"\n" +
	"\x1boss/v1/upload_session.proto\x12\x06oss.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x03\n" +
	"\rUploadSession\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x04R\bfileSize\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x04 \x01(\rR\tchunkSize\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x04R\x06offset\x123\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1b.oss.v1.UploadSessionStatusR\x06status\x12\x16\n" +
	"\x06sha256\x18\a \x01(\tR\x06sha256\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xc0\x01\n" +
	"\x1aCreateUploadSessionRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x04R\bfileSize\x12'\n" +
	"\x0fpreferred_chunk\x18\x04 \x01(\rR\x0epreferredChunk\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\"6\n" +
	"\x17GetUploadSessionRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\"f\n" +
	"\x1bCreateUploadSessionResponse\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.oss.v1.UploadSessionR\asession\x12\x16\n" +
	"\x06reused\x18\x02 \x01(\bR\x06reused\"K\n" +
	"\x18GetUploadSessionResponse\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.oss.v1.UploadSessionR\asession*\xa9\x01\n" +
	"\x13UploadSessionStatus\x12%\n" +
	"!UPLOAD_SESSION_STATUS_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fUPLOAD_SESSION_STATUS_UPLOADING\x10\x01\x12#\n" +
	"\x1fUPLOAD_SESSION_STATUS_COMPLETED\x10\x02\x12!\n" +
	"\x1dUPLOAD_SESSION_STATUS_ABORTED\x10\x032\xd1\x01\n" +
	"\x14UploadSessionService\x12`\n" +
	"\x13CreateUploadSession\x12\".oss.v1.CreateUploadSessionRequest\x1a#.oss.v1.CreateUploadSessionResponse\"\x00\x12W\n" +
	"\x10GetUploadSession\x12\x1f.oss.v1.GetUploadSessionRequest\x1a .oss.v1.GetUploadSessionResponse\"\x00B<Z:github.com/aureate7/mini-oss/service_proto/pb/oss/v1;ossv1b\x06proto3"

var (
	file_oss_v1_upload_session_proto_rawDescOnce sync.Once
	file_oss_v1_upload_session_proto_rawDescData []byte
)

func file_oss_v1_upload_session_proto_rawDescGZIP() []byte {
	file_oss_v1_upload_session_proto_rawDescOnce.Do(func() {
		file_oss_v1_upload_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oss_v1_upload_session_proto_rawDesc), len(file_oss_v1_upload_session_proto_rawDesc)))
	})
	return file_oss_v1_upload_session_proto_rawDescData
}

var file_oss_v1_upload_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_oss_v1_upload_session_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_oss_v1_upload_session_proto_goTypes = []any{
	(UploadSessionStatus)(0),            // 0: oss.v1.UploadSessionStatus
	(*UploadSession)(nil),               // 1: oss.v1.UploadSession
	(*CreateUploadSessionRequest)(nil),  // 2: oss.v1.CreateUploadSessionRequest
	(*GetUploadSessionRequest)(nil),     // 3: oss.v1.GetUploadSessionRequest
	(*CreateUploadSessionResponse)(nil), // 4: oss.v1.CreateUploadSessionResponse
	(*GetUploadSessionResponse)(nil),    // 5: oss.v1.GetUploadSessionResponse
	(*timestamppb.Timestamp)(nil),       // 6: google.protobuf.Timestamp
}
var file_oss_v1_upload_session_proto_depIdxs = []int32{
	0, // 0: oss.v1.UploadSession.status:type_name -> oss.v1.UploadSessionStatus
	6, // 1: oss.v1.UploadSession.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: oss.v1.UploadSession.updated_at:type_name -> google.protobuf.Timestamp
	6, // 3: oss.v1.UploadSession.expires_at:type_name -> google.protobuf.Timestamp
	1, // 4: oss.v1.CreateUploadSessionResponse.session:type_name -> oss.v1.UploadSession
	1, // 5: oss.v1.GetUploadSessionResponse.session:type_name -> oss.v1.UploadSession
	2, // 6: oss.v1.UploadSessionService.CreateUploadSession:input_type -> oss.v1.CreateUploadSessionRequest
	3, // 7: oss.v1.UploadSessionService.GetUploadSession:input_type -> oss.v1.GetUploadSessionRequest
	4, // 8: oss.v1.UploadSessionService.CreateUploadSession:output_type -> oss.v1.CreateUploadSessionResponse
	5, // 9: oss.v1.UploadSessionService.GetUploadSession:output_type -> oss.v1.GetUploadSessionResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_oss_v1_upload_session_proto_init() }
func file_oss_v1_upload_session_proto_init() {
	if File_oss_v1_upload_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oss_v1_upload_session_proto_rawDesc), len(file_oss_v1_upload_session_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oss_v1_upload_session_proto_goTypes,
		DependencyIndexes: file_oss_v1_upload_session_proto_depIdxs,
		EnumInfos:         file_oss_v1_upload_session_proto_enumTypes,
		MessageInfos:      file_oss_v1_upload_session_proto_msgTypes,
	}.Build()
	File_oss_v1_upload_session_proto = out.File
	file_oss_v1_upload_session_proto_goTypes = nil
	file_oss_v1_upload_session_proto_depIdxs = nil
}
